import { Project } from "@/types";

export const projectData: Project[] = [
    {
        id: 1,
        name: "Programming projects",
        techStack: ["/ts.png", "/node.jpg"],
        category: "Programming",
        description: "TypeScript and Node.js programs had been developed and published on Node Package Manager NPM.",
        github: "https://github.com/Ahsan2001/Learning-TypeScript/tree/projects",
        detail: [
            {
                title: "Simple Command Line Calculator",
                description: "A simple command line calculator using TypeScipt, Node.js and Inquirer",
                links: "https://www.npmjs.com/package/ahsan-cli-calculator",
            },
            {
                title: "Number Guessing Game",
                description: "This guess the number game is a short TypeScript/Node.js project that allows the user to guess the number generated by the computer.",
                links: "https://www.npmjs.com/package/ahsan-guess-number",
            },
            {
                title: "ATM",
                description: "This somewhat complex TypeScript/Node.js project is a console-based application. When the system starts the user is prompted with a user id and user pin. After entering the details successfully, the ATM functionalities are unlocked. All the user data is generated randomly.",
                links: "https://www.npmjs.com/package/ahsan-atm-project",
            },
            {
                title: "Todo List",
                description: "Develop a simple command line Todo app using TypeScipt, Node.js and Inquirer.",
                links: "https://www.npmjs.com/package/ahsan-todo-project",
            },
            {
                title: "Word Counter",
                description: "The user will enter a english paragraph and all that is needed is to just to implement counting characters and words without whitespaces.",
                links: "https://www.npmjs.com/package/ahsan-word-counter",
            },
            {
                title: "Currency Converter",
                description: "The TypeScript console app is used to convert currencies: the users enter a certain amount of money in one currency and set the currency they want to check the monetary value of.",
                links: "https://www.npmjs.com/package/ahsan-currency-converter",
            },
            {
                title: "Student Management System",
                description: "This project is a simple console based Student Management System. In this project you will be learning how to add new students, how to generate a 5 digit unique studentID for each student, how to enroll students in the given courses. Also, you will be implementing the following operations enroll, view balance, pay tuition fees, show status, etc. The status will show all the details of the student including name, id, courses enrolled and balance.",
                links: "https://www.npmjs.com/package/ahsan-student-management-system-07",
            },
            {
                title: "Text-Based Adventure-Game",
                description: "This project is not GUI based. It is a console-based game. The video here shows how to develop the game in Java. You will take the requirements of the game from the video and develop the game in TypeScript and Node.js",
                links: "https://www.npmjs.com/package/ahsan-adventure-game",
                videoLink: "https://www.youtube.com/watch?v=EpB9u4ItOYU&t=1s",
            },
            {
                title: "Quiz System",
                description: "The app will show the students multiple choice questions and promt the user to reply. In the end it will show the students the result of the quiz.",
                links: "https://www.npmjs.com/package/ahsan-quiz-system",
            },
            {
                title: "Countdown Timer",
                description: "In this project, you will build a countdown timer using the date module.",
                links: "https://www.npmjs.com/package/ahsan-countdown-timer",
            },
        ]
    },
    {
        id: 2,
        name: "Programming projects",
        techStack: ["/js.png", "/node.jpg"],
        category: "Programming",
        description: "Completed 44 Javascript and Node.js problems. View all programs in github link",
        github: "https://github.com/Ahsan2001/JavaScript-and-Node.js",
        detail: [
            {
                title: "Print Personal Message",
                description: "Store a person’s name in a variable, and print a message to that person. Your message should be simple, such as, “Hello Eric, would you like to learn some Python today?”",
                links: "http://js-assignment-ahsan.surge.sh/Personal_Message/index.html",
            },
            {
                title: "Name Cases",
                description: "Store a person’s name in a variable, and then print that person’s name in lowercase, uppercase, and titlecase.",
                links: "http://js-assignment-ahsan.surge.sh/Name_Cases/index.html",
            },
            {
                title: "Famous Quote",
                description: "Store the famous person’s name in a variable called famous_person. Then compose your message and store it in a new variable called message. Print your message.",
                links: "http://js-assignment-ahsan.surge.sh/Famous_Quote_2/index.html",
            },
            {
                title: "Stripping Names",
                description: "Store a person’s name, and include some whitespace characters at the beginning and end of the name. Make sure you use each character combination, \t and \n, at least once. Print the name once, so the whitespace around the name is displayed. Then print the name after striping the white spaces.",
                links: "http://js-assignment-ahsan.surge.sh/Stripping_Names/index.html",
            },
            {
                title: "Create Four Line",
                description: "Your output should simply be four lines with the number 8 appearing once on each line.",
                links: "http://js-assignment-ahsan.surge.sh/Create_Four_Lines/index.html",
            },
            {
                title: "City Names",
                description: "Write a function called city_country() that takes in the name of a city and its country. The function should return a string formatted like this Lahore, Pakistan  Call your function with at least three city-country pairs, and print the value that’s returned.",
                links: "http://js-assignment-ahsan.surge.sh/City_Names/index.html",
            },
            {
                title: "Album",
                description: "Write a function called make_album() that builds a Object describing a music album. The function should take in an artist name and an album title, and it should return a Object containing these two pieces of information. Use the function to make three dictionaries representing different albums. Print each return value to show that Objects are storing the album information correctly. Add an optional parameter to make_album() that allows you to store the number of tracks on an album. If the calling line includes a value for the number of tracks, add that value to the album’s Object. Make at least one new function call that includes the number of tracks on an album.",
                links: "http://js-assignment-ahsan.surge.sh/Album/index.html",
            },
            {
                title: "Adding Comments",
                description: "Choose two of the programs you’ve written, and add at least one comment to each. If you don’t have anything specific to write because your programs are too simple at this point, just add your name and the current date at the top of each program file. Then write one sentence describing what the program does.",
                links: "http://js-assignment-ahsan.surge.sh/Adding_Comments/index.html",
            },
            {
                title: "Names",
                description: "Store the names of a few of your friends in a array called names. Print each person’s name by accessing each element in the list, one at a time.",
                links: "http://js-assignment-ahsan.surge.sh/Names/index.html",
            }, {
                title: "Greetings",
                description: "Start with the array you used in previous Exercise , but instead of just printing each person’s name, print a message to them. The text of each message should be the same, but each message should be personalized with the person’s name.",
                links: "http://js-assignment-ahsan.surge.sh/Greetings/index.html",
            }, {
                title: "Your Own Array",
                description: "Think of your favorite mode of transportation, such as a motorcycle or a car, and make a list that stores several examples. Use your list to print a series of statements about these items, such as “I would like to own a Honda motorcycle.”",
                links: "http://js-assignment-ahsan.surge.sh/Your_Own_Array/index.html",
            }, {
                title: "Guest List",
                description: "If you could invite anyone, living or deceased, to dinner, who would you invite? Make a list that includes at least three people you’d like to invite to dinner. Then use your list to print a message to each person, inviting them to dinner.",
                links: "http://js-assignment-ahsan.surge.sh/Guest_List/index.html",
            }, {
                title: "Cars",
                description: "Write a function that stores information about a car in a Object. The function should always receive a manufacturer and a model name. It should then accept an arbitrary number of keyword arguments. Call the function with the required information and two other name-value pairs, such as a color or an optional feature. Print the Object that’s returned to make sure all the information was stored correctly.",
                links: "http://js-assignment-ahsan.surge.sh/Cars/index.html",
            }, {
                title: "Sandwiches",
                description: "Write a function that accepts a array of items a person wants on a sandwich. The function should have one parameter that collects as many items as the function call provides, and it should print a summary of the sandwich that is being ordered. Call the function three times, using a different number of arguments each time.",
                links: "http://js-assignment-ahsan.surge.sh/Sandwiches/index.html",
            }, {
                title: "Hello Admin",
                description: "Make a array of five or more usernames, including the name 'admin'. Imagine you are writing code that will print a greeting to each user after they log in to a website. Loop through the array, and print a greeting to each user: If the username is 'admin', print a special greeting, such as Hello admin, would you like to see a status report?  Otherwise, print a generic greeting, such as Hello Eric, thank you for logging in again. ",
                links: "http://js-assignment-ahsan.surge.sh/Hello_Admin/index.html",
            }, {
                title: "Large Shirts",
                description: "Modify the make_shirt() function so that shirts are large by default with a message that reads I love JavaScript. Make a large shirt and a medium shirt with the default message, and a shirt of any size with a different message.",
                links: "http://js-assignment-ahsan.surge.sh/Large_Shirts/index.html",
            },


        ]
    },
    {
        id: 3,
        name: "Custom Html & Php Brand project",
        techStack: ["/html.png", "/css.png", "/php.png", "/js.png",],
        category: "Brands",
        description: "Utilized cutting-edge frontend technologies, including HTML5, CSS3 & JavaScript to create a visually appealing and responsive website layout",
        github: "https://github.com/Ahsan2001",
        detail: [
            {
                title: "Project: Amazon Web Design Inc. Website Development",
                description: `Developed and launched the official website for Amazon Web Design Inc., 
                showcasing the company's web development expertise. Responsible for both frontend and backend development, 
                ensuring a seamless user experience, responsive design, and robust security measures. 
                Collaborated closely with the design team, optimized performance, and implemented cross-browser compatibility. 
                Demonstrated strong problem-solving skills and technical expertise, 
                resulting in a visually appealing and highly functional website.`,
                links: "https://amazonwebdesigninc.com/",
            },

            {
                title: "Project: Prime Authors. Book Writing Brand",
                description: `Worked closely with the design team, fostering seamless collaboration and translating design concepts into functional web elements. Implemented design optimizations for enhanced performance and superior aesthetics. Ensured the website's compatibility across various browsers and devices, guaranteeing a consistent and user-friendly experience for all visitors.  The brand is developed by Html, css , bootstrap , jquery, javascript and core php for form handling`,
                links: "https://primeauthors.com/publishing.php",
            },

            {
                title: "Project: Web Craftive Studios. Website Development",
                description: `Collaborated closely with the design team, optimized performance, and implemented cross-browser compatibility. 
                Demonstrated strong problem-solving skills and technical expertise . The brand is developed by Html, css , bootstrap , jquery, javascript and core php for form handling`,
                links: "https://webcraftivestudios.com/",
            },


            {
                title: "Project: Designtech 24/7. Digital Services Brand",
                description: `Collaborated closely with the design team, optimized performance, and implemented cross-browser compatibility. 
                Demonstrated strong problem-solving skills and technical expertise . The brand is developed by Html, css , bootstrap , jquery, javascript and core php for form handling`,
                links: "https://www.designtech247.com/",
            },

            {
                title: "Project: Canvas Web Studios. Website Development",
                description: `Developed and launched the official website for Amazon Web Design Inc., 
                showcasing the company's web development expertise. Responsible for both frontend and backend development, 
                ensuring a seamless user experience, responsive design, and robust security measures. 
                Collaborated closely with the design team, optimized performance, and implemented cross-browser compatibility. 
                Demonstrated strong problem-solving skills and technical expertise. The brand is developed by Html, css , bootstrap , jquery, javascript and core php for form handling`,
                links: "https://canvaswebstudios.com/",
            },

            {
                title: "Project: Elite Book Authors. Book Writing Brand",
                description: `Worked closely with the design team, fostering seamless collaboration and translating design concepts into functional web elements. Implemented design optimizations for enhanced performance and superior aesthetics. Ensured the website's compatibility across various browsers and devices, guaranteeing a consistent and user-friendly experience for all visitors.  The brand is developed by Html, css , bootstrap , jquery, javascript and core php for form handling`,
                links: "https://elitebookauthors.com/amazon-publishing",
            },

        ]
    },
    {
        id: 4,
        name: "React Custom Images Creating Dashboard",
        techStack: ["/react.png","/mu.png"],
        category: "React",
        description: "Complete Dynamic Frontend coding the technologies i used in this project is React version 18. Redux for state management and material ui library to design the frontend client view.",
        github: "https://github.com/Ahsan2001/",
        detail: [
            {
                title: "Project: Aumana Org . React Custom Images Creating Dashboard",
                description: "Worked closely with the design team, fostering seamless collaboration and translating design concepts into functional web elements. Implemented design optimizations for enhanced performance and superior aesthetics. Ensured the website's compatibility across various browsers and devices, guaranteeing a consistent and user-friendly experience for all visitors.  The Peoject is developed by React, Redux , Axios , Custom javascript and material ui for styling",
                links: "https://www.aumana.org/",
            },
        ]
    },

    {
        id: 5,
        name: "Personal Portfolio Website",
        techStack: ["/next.png","/ts.png", "/mu.png"],
        description: "Utilized cutting-edge frontend technologies, including Typescript, Nextjs & Material Ui to create a visually appealing and responsive website layout",
        category: "React",
        github: "https://github.com/Ahsan2001/Portfolio-Ahsan-Shaikh",
        detail: [
            {
                title: "Personal Portfolio Website",
                description: "Enhance user experience by implementing a dynamic dark and light mode feature. Users can seamlessly switch between visually comfortable dark and light themes, ensuring readability and reducing eye strain in various lighting conditions. Implement a dynamic page creation system that allows users or administrators to create and customize pages effortlessly. Whether it's adding new content, rearranging elements, or updating information, the platform provides an intuitive interface for dynamic page management.",
                links: "https://portfolio-ahsan-shaikh.vercel.app/",
            },
        ]
    },


  {
        id: 10,
        name: "Movie Website ",
        techStack: ["/js.png" ,"/react.png", "/sass.png"],
        description: "Infinite Scroll Api, Lazy Loading, Skeleton Loading",
        category: "React",
        github: "https://github.com/Ahsan2001/TMDB-MOVIX/tree/main",
        detail: [
            {
                title: "Project: React Movie Website using tmdb apis",
                description: `Movix: Elevate your entertainment experience! This web app caters to film and TV enthusiasts, offering a curated selection of trending content. Explore detailed information and captivating trailers within a user-friendly interface. Your gateway to the world of cinematic enjoyment! 🍿`,
                links: "https://tmdb-movix-seven.vercel.app/",
            },
        ]
    },

    
    {
        id: 6,
        name: "Full Stack Blog App Website",
        techStack: ["/mongo.png","/react.png","/ts.png", "/mu.png", "/node.jpg"],
        description: "React and Material Ui for create a visually appealing and responsive website layout and Nodejs For backend Development",
        category: "React",
        github: "https://github.com/Ahsan2001/personal-blog-app",
        detail: [
            {
                title: "Project: Blog App - React, Node, MongoDB  Website",
                description: `User Authentication
                Users can create an account with their name, username, email address and password.
                Users can log in with their registered username and password.
                User passwords are securely hashed and stored in the database using bcrypt.
                Authentication is implemented using JWT (JSON Web Tokens)
                Users can view a list of Blogs and detail page
                Users can comment on any blog
                Users can post a blog with author name, date, title, content, and blog image
                Image is store in cloudinary platform
                Only Admin Users can Edit and Delete Functionality in blog
                Functionalities are protected by role-based access control (RBAC), ensuring that only authenticated`,
                links: "https://personal-blog-app-frontend.vercel.app/",
            },
        ]
    },




    {
        id: 7,
        name: "Full Stack Resturant Web App Website",
        techStack: ["/js.png" ,"/mongo.png","/react.png", "/mu.png", "/node.jpg"],
        description: "React and Material Ui for create a visually appealing and responsive website layout and Nodejs For backend Development",
        category: "React",
        github: "https://github.com/Ahsan2001/restaurant-web-application",
        detail: [
            {
                title: "Project: Blog App - React, Node, MongoDB  Website",
                description: `User Authentication
                Users can create an account with their name, username, email address and password.
                Users can log in with their registered username and password.
                User passwords are securely hashed and stored in the database using bcrypt.
                Authentication is implemented using JWT (JSON Web Tokens)
                Users can view a list of Menu and detail page
                Users can comment on any Menu
                admin can post a Menu with  name, title, content, and food image
                Image is store in cloudinary platform
                Only Admin Users can Edit and Delete Functionality in blog
                Functionalities are protected by role-based access control (RBAC), ensuring that only authenticated`,
                links: "https://github.com/Ahsan2001/restaurant-web-application",
            },
        ]
    },


    {
        id: 8,
        name: "React Admin Panel Dashboard",
        techStack: ["/react.png","/b.png"],
        category: "React",
        description: "Complete Dynamic Frontend coding the technologies i used in this project is React version 18. Redux for state management and Bootstrap 5 library to design the frontend client view.",
        github: "https://github.com/Ahsan2001/Admin-Panel",
        detail: [
            {
                title: "Project: Aumana Org . React Custom Images Creating Dashboard",
                description: "Worked closely with the design team, fostering seamless collaboration and translating design concepts into functional web elements. Implemented design optimizations for enhanced performance and superior aesthetics. Ensured the website's compatibility across various browsers and devices, guaranteeing a consistent and user-friendly experience for all visitors.  The Peoject is developed by React, Redux , Axios , Custom javascript and material ui for styling",
                links: "https://github.com/Ahsan2001/Admin-Panel",
            },
        ]
    },





    {
        id: 9,
        name: "Full Stack Contact Web App Website",
        techStack: ["/react.png", "/node.jpg"],
        description: "React and Material Ui for create a visually appealing and responsive website layout and Nodejs For backend Development",
        category: "React",
        github: "https://github.com/Ahsan2001/Contact_App/tree/master",
        detail: [
            {
                title: "Project: Contact App - React, Node, MongoDB  Website",
                description: `Simple Crud Opertion Perform in Both Frontend And Backend`,
                links: "https://github.com/Ahsan2001/Contact_App/tree/master",
            },
        ]
    },














]
